# Site settings
title: Jordan Eldredge
email: jordan@jordaneldredge.com
author: Jordan Eldredge
description: > # this means to ignore newlines until "baseurl:"
    Hello! My name is Jordan Eldredge. I am a programmer and classical singer
    living in San Francisco with my wife, and fellow singer, Chelsea Hollow.
url: "https://jordaneldredge.com" # the base hostname & protocol for your site
twitter_username: captbaritone
github_username:  captbaritone
youtube_username:  captbaritone
timezone: America/Los_Angeles
google_analytics: UA-96948-15

# Where things are
destination: ./public_html
keep_files:
    - singer
    - projects
    - share_until
    - .htaccess
    - talks
    - winamp2-js.js

#Pixyll features
show_related_posts: false
show_post_footers: true
read_time: false

sass:
  style: compressed

# Outputting
permalink: /blog/:title

# Build settings
markdown: kramdown
highlight: false
animated: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
