packages:
  - packages/*
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
catalog:
  '@types/better-sqlite3': ^7.6.12
  better-sqlite3: ^11.5.0
patchedDependencies:
  shiki@0.11.1: patches/shiki@0.11.1.patch
  notion-to-md: patches/notion-to-md.patch
overrides:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
