/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import queryBlogPostsResolver from "./../../../lib/data/ContentConnection";
import queryGetContentBySlugResolver from "./../../../lib/data/Content";
import queryNotesResolver from "./../../../lib/data/ContentConnection";
import querySearchResolver from "./../../../lib/data/ContentConnection";
import { GraphQLSchema, GraphQLObjectType, GraphQLList, GraphQLNonNull, GraphQLString, GraphQLInt, GraphQLBoolean, GraphQLEnumType } from "graphql";
import { AudioFile as queryAudioFilesResolver } from "./../../../lib/data/AudioFile";
import { getVc } from "./route";
import { Tag as queryGetTagByNameResolver } from "./../../../lib/data/Tag";
import { Image as queryImagesResolver } from "./../../../lib/data/Image";
import { Link as queryLinksResolver } from "./../../../lib/data/Link";
import { Paste as queryMyPastesResolver, Paste as queryPasteResolver, Paste as mutationCreatePasteResolver, Paste as mutationDeletePasteResolver, Paste as mutationUpdatePasteResolver } from "./../../../lib/data/Paste";
import { Tweet as queryTweetsResolver } from "./../../../lib/data/Tweet";
import { YoutubeVideo as queryYoutubeVideosResolver } from "./../../../lib/data/YoutubeVideo";
export function getSchema(): GraphQLSchema {
    const AudioFileType: GraphQLObjectType = new GraphQLObjectType({
        name: "AudioFile",
        description: "An audio file which has been embedded in a piece of content.",
        fields() {
            return {
                src: {
                    name: "src",
                    type: GraphQLString
                },
                url: {
                    name: "url",
                    type: GraphQLString
                }
            };
        }
    });
    const ImageType: GraphQLObjectType = new GraphQLObjectType({
        name: "Image",
        description: "An image which has been embedded in a piece of content.",
        fields() {
            return {
                height: {
                    name: "height",
                    type: GraphQLInt
                },
                src: {
                    name: "src",
                    type: GraphQLString
                },
                width: {
                    name: "width",
                    type: GraphQLInt
                }
            };
        }
    });
    const LinkType: GraphQLObjectType = new GraphQLObjectType({
        name: "Link",
        description: "A link which has been embedded in a piece of content.",
        fields() {
            return {
                url: {
                    name: "url",
                    type: GraphQLString
                }
            };
        }
    });
    const TweetType: GraphQLObjectType = new GraphQLObjectType({
        name: "Tweet",
        description: "A Tweet which has been embedded in a piece of content.",
        fields() {
            return {
                statusId: {
                    name: "statusId",
                    type: GraphQLString
                },
                url: {
                    name: "url",
                    type: GraphQLString
                }
            };
        }
    });
    const YoutubeVideoType: GraphQLObjectType = new GraphQLObjectType({
        name: "YoutubeVideo",
        description: "A Youtube video which has been embedded in a piece of content.",
        fields() {
            return {
                embedUrl: {
                    name: "embedUrl",
                    type: GraphQLString
                },
                thumbnailUrl: {
                    name: "thumbnailUrl",
                    type: GraphQLString
                },
                token: {
                    name: "token",
                    type: GraphQLString
                },
                url: {
                    name: "url",
                    type: GraphQLString
                },
                vertical: {
                    name: "vertical",
                    type: GraphQLBoolean
                }
            };
        }
    });
    const MarkdownType: GraphQLObjectType = new GraphQLObjectType({
        name: "Markdown",
        description: "Content that can be represented as markdown.",
        fields() {
            return {
                audioFiles: {
                    name: "audioFiles",
                    type: new GraphQLList(new GraphQLNonNull(AudioFileType))
                },
                images: {
                    name: "images",
                    type: new GraphQLList(new GraphQLNonNull(ImageType))
                },
                links: {
                    name: "links",
                    type: new GraphQLList(new GraphQLNonNull(LinkType))
                },
                markdownString: {
                    description: "The content encoded as a markdown string.",
                    name: "markdownString",
                    type: GraphQLString
                },
                tweets: {
                    name: "tweets",
                    type: new GraphQLList(new GraphQLNonNull(TweetType))
                },
                youtubeVideos: {
                    name: "youtubeVideos",
                    type: new GraphQLList(new GraphQLNonNull(YoutubeVideoType))
                }
            };
        }
    });
    const SiteUrlType: GraphQLObjectType = new GraphQLObjectType({
        name: "SiteUrl",
        description: "A URL on the site.",
        fields() {
            return {
                fullyQualified: {
                    description: "The fully qualified URL.",
                    name: "fullyQualified",
                    type: GraphQLString
                },
                path: {
                    description: "Just the path portion of the URL. Excludes the protocol and domain\n\nUseful for links within the site.",
                    name: "path",
                    type: GraphQLString
                }
            };
        }
    });
    const TagType: GraphQLObjectType = new GraphQLObjectType({
        name: "Tag",
        description: "A tag that can be associated with items.",
        fields() {
            return {
                items: {
                    description: "The list of items that have this tag.",
                    name: "items",
                    type: new GraphQLList(new GraphQLNonNull(ContentType)),
                    resolve(source, _args, context) {
                        return source.items(getVc(context));
                    }
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                url: {
                    name: "url",
                    type: SiteUrlType
                }
            };
        }
    });
    const TagSetType: GraphQLObjectType = new GraphQLObjectType({
        name: "TagSet",
        fields() {
            return {
                tags: {
                    name: "tags",
                    type: new GraphQLList(new GraphQLNonNull(TagType))
                }
            };
        }
    });
    const TTSAudioType: GraphQLObjectType = new GraphQLObjectType({
        name: "TTSAudio",
        description: "Auto generated audio for a content item.",
        fields() {
            return {
                byteLength: {
                    name: "byteLength",
                    type: GraphQLInt
                },
                content: {
                    name: "content",
                    type: ContentType
                },
                lastUpdated: {
                    name: "lastUpdated",
                    type: GraphQLInt
                },
                url: {
                    name: "url",
                    type: GraphQLString
                },
                vanityUrl: {
                    name: "vanityUrl",
                    type: SiteUrlType
                }
            };
        }
    });
    const ContentType: GraphQLObjectType = new GraphQLObjectType({
        name: "Content",
        fields() {
            return {
                content: {
                    name: "content",
                    type: MarkdownType
                },
                date: {
                    description: "YYYY-MM-DD in Local Time (PST)",
                    name: "date",
                    type: GraphQLString
                },
                markdownUrl: {
                    description: "Url to download the post as a markdown file.",
                    name: "markdownUrl",
                    type: SiteUrlType
                },
                slug: {
                    name: "slug",
                    type: GraphQLString
                },
                summary: {
                    name: "summary",
                    type: GraphQLString
                },
                summaryImage: {
                    name: "summaryImage",
                    type: GraphQLString
                },
                tagSet: {
                    name: "tagSet",
                    type: TagSetType
                },
                title: {
                    name: "title",
                    type: GraphQLString
                },
                ttsAudio: {
                    description: "The audio version of this content, if it exists.",
                    name: "ttsAudio",
                    type: TTSAudioType
                },
                url: {
                    name: "url",
                    type: SiteUrlType
                }
            };
        }
    });
    const PasteType: GraphQLObjectType = new GraphQLObjectType({
        name: "Paste",
        description: "A paste \u2014 a snippet of text content hosted on the site.",
        fields() {
            return {
                content: {
                    name: "content",
                    type: GraphQLString
                },
                createdAt: {
                    name: "createdAt",
                    type: GraphQLString
                },
                fileName: {
                    name: "fileName",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                rawUrl: {
                    name: "rawUrl",
                    type: GraphQLString
                },
                size: {
                    name: "size",
                    type: GraphQLInt
                },
                url: {
                    name: "url",
                    type: GraphQLString
                }
            };
        }
    });
    const SortOptionType: GraphQLEnumType = new GraphQLEnumType({
        name: "SortOption",
        values: {
            best: {
                value: "best"
            },
            latest: {
                value: "latest"
            }
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                audioFiles: {
                    name: "audioFiles",
                    type: new GraphQLList(new GraphQLNonNull(AudioFileType)),
                    resolve() {
                        return queryAudioFilesResolver.audioFiles();
                    }
                },
                blogPosts: {
                    description: "Formal write-ups of projects and ideas.",
                    name: "blogPosts",
                    type: new GraphQLList(new GraphQLNonNull(ContentType)),
                    resolve(_source, _args, context) {
                        return queryBlogPostsResolver.blogPosts(getVc(context));
                    }
                },
                getContentBySlug: {
                    description: "Find a piece of content by its slug.",
                    name: "getContentBySlug",
                    type: ContentType,
                    args: {
                        slug: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args, context) {
                        return queryGetContentBySlugResolver.getBySlug(getVc(context), args.slug);
                    }
                },
                getTagByName: {
                    description: "Get a tag by name.",
                    name: "getTagByName",
                    type: TagType,
                    args: {
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return queryGetTagByNameResolver.getTagByName(args.name);
                    }
                },
                images: {
                    name: "images",
                    type: new GraphQLList(new GraphQLNonNull(ImageType)),
                    resolve() {
                        return queryImagesResolver.images();
                    }
                },
                links: {
                    name: "links",
                    type: new GraphQLList(new GraphQLNonNull(LinkType)),
                    resolve() {
                        return queryLinksResolver.links();
                    }
                },
                myPastes: {
                    description: "List the current user's pastes.",
                    name: "myPastes",
                    type: new GraphQLList(new GraphQLNonNull(PasteType)),
                    resolve(_source, _args, context) {
                        return queryMyPastesResolver.myPastes(getVc(context));
                    }
                },
                notes: {
                    description: "Quick thoughts, observations, and links.",
                    name: "notes",
                    type: new GraphQLList(new GraphQLNonNull(ContentType)),
                    resolve(_source, _args, context) {
                        return queryNotesResolver.notes(getVc(context));
                    }
                },
                paste: {
                    description: "Get a single paste by ID (must be owned by the current user, or user is admin).",
                    name: "paste",
                    type: PasteType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args, context) {
                        return queryPasteResolver.paste(getVc(context), args.id);
                    }
                },
                search: {
                    description: "Search for content by title, content, or tags.",
                    name: "search",
                    type: new GraphQLList(new GraphQLNonNull(ContentType)),
                    args: {
                        first: {
                            type: GraphQLInt
                        },
                        query: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        sort: {
                            type: new GraphQLNonNull(SortOptionType)
                        }
                    },
                    resolve(_source, args, context) {
                        return querySearchResolver.search(getVc(context), args.query, args.sort, args.first);
                    }
                },
                tweets: {
                    name: "tweets",
                    type: new GraphQLList(new GraphQLNonNull(TweetType)),
                    resolve() {
                        return queryTweetsResolver.tweets();
                    }
                },
                youtubeVideos: {
                    name: "youtubeVideos",
                    type: new GraphQLList(new GraphQLNonNull(YoutubeVideoType)),
                    resolve() {
                        return queryYoutubeVideosResolver.youtubeVideos();
                    }
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                createPaste: {
                    description: "Create a new paste.",
                    name: "createPaste",
                    type: PasteType,
                    args: {
                        content: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        fileName: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args, context) {
                        return mutationCreatePasteResolver.createPaste(getVc(context), args.fileName, args.content);
                    }
                },
                deletePaste: {
                    description: "Delete a paste.",
                    name: "deletePaste",
                    type: GraphQLBoolean,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args, context) {
                        return mutationDeletePasteResolver.deletePaste(getVc(context), args.id);
                    }
                },
                updatePaste: {
                    description: "Update an existing paste.",
                    name: "updatePaste",
                    type: PasteType,
                    args: {
                        content: {
                            type: GraphQLString
                        },
                        fileName: {
                            type: GraphQLString
                        },
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args, context) {
                        return mutationUpdatePasteResolver.updatePaste(getVc(context), args.id, args.fileName, args.content);
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        mutation: MutationType,
        types: [SortOptionType, AudioFileType, ContentType, ImageType, LinkType, MarkdownType, MutationType, PasteType, QueryType, SiteUrlType, TTSAudioType, TagType, TagSetType, TweetType, YoutubeVideoType]
    });
}
